version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: petclinic_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petclinic_backend
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8081:8080"  # host:container (Spring Boot uses 8080 inside container)

volumes:
  mysql_data:
